local-phone-apps :=  \
				abpaccess \
				ApplicationsProvider \
				BackupRestoreConfirmation \
				Bluetooth \
				BqPmuRegTool \
				Camera \
				CertInstaller \
				DefaultContainerService \
				DrmProvider \
				DVFSSwitcher \
				FaceUnlock2 \
				FlashLight \
				HiFiMode \
				HoloSpiralWallpaper \
				KeyChain \
				KTDaemon \
				KtLogControl \
				LiveWallpapers \
				LiveWallpapersPicker \
				MediaProvider \
				MMI \
				Nfc \
				NoiseField \
				NvCPLSvc \
				PhaseBeam \
				PowerBlance \
				PowerSave \
				SharedStorageBackup \
				SoundRecorder \
				UARTSwitch \
				UsbConnectionMode \
				UserDictionaryProvider \
				VisualizationWallpapers \

